myproject/myapp/urls.py
from django.urls import path
from .views import *

from . import views

app_name = 'myapp'
urlpatterns = [
    path('', Deshboard.as_view(), name='Deshboard'),
    path('DailyReportView', DailyReportView.as_view(), name='DailyReportView'),
    path('CreateDailyReport', CreateDailyReport.as_view(), name = 'CreateDailyReport'),
    path('OrderQtyCreate', OrderQtyCreate.as_view(), name= 'OrderQtyCreate'),
    path('FilterbyBuyerReport', FilterbyBuyerReport.as_view(), name = 'FilterbyBuyerReport'),
    path('FilterbyLineReport', FilterbyLineReport.as_view(), name = 'FilterbyLineReport'),
    path('FilterbyStyleReport', FilterbyStyleReport.as_view(), name='FilterbyStyleReport'),
    path('DataEntryEdit/<int:pk>/', DataEntryEdit.as_view(), name= 'DataEntryEdit'),
    path('StyleCreate', StyleCreate.as_view(), name='StyleCreate'),
    path('BuyerCreate', BuyerCreate.as_view(), name='BuyerCreate'),
    path('ItemCreate', ItemCreate.as_view(), name='ItemCreate'),
    path('InputQtyCreate', InputQtyCreate.as_view(), name='InputQtyCreate'),
    path('MenPower', MenPower.as_view(), name='MenPower'),
    path('ProductionShit', ProductionShitView.as_view(), name='ProductionShit'),
    path('ProductionShfitEdit/<int:pk>/', ProductionShfitEdit.as_view(), name='ProductionShfitEdit'),
    path('login/',UserLoginView.as_view(), name='UserLoginView'),
    path('logout/', UserLogoutView.as_view(), name='UserLogoutView'),

]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]

myproject/templates/BuyerCreate.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="card border-success mb-3" style="max-width: 50rem;">
  <div class="card-header bg-success">Buyer Style</div>
  <div class="card-body text-success">
<form method="POST">{% csrf_token %}

    <div class="col-md-12">
                <div class="form-group">
                  <label>Buyer Name</label>
                  <input type="text" class="form-control" name="BuyerName">
                </div>
              </div>

  <div class="col-md-12">
                <div class="form-group">
                  <label>Address</label>
                  <input type="text" class="form-control" name="Address">
                </div>
              </div>



     <div class="col-md-12">
<!--                <div class="form-group">-->
<!--                  <label>Date</label>-->
                  <input type="submit" name="Create" class="btn btn-success">
<!--                </div>-->
              </div>




</form>



  </div>
</div>

<!--=========================================-->

 <div class="card">
              <div class="card-header">

<h5><b>Buyer List</b></h5>

              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>


                  <th>Buyer</th>
                  <th>Address</th>


                  </tr>

                  </thead>
                  <tbody>
                  {% for d in buyer %}
                <tr>
                  <td>{{d.BuyerName}}</td>
                  <td>{{d.Address}}</td>


                </tr>
                {% endfor %}

                  </tbody>
                  <tfoot>
                  <tr>


                  <th></th>
                  <th></th>



                  </tr>

                  </tfoot>
                </table>
              </div>
              <!-- /.card-body -->
            </div>

{% endblock content %}

myproject/templates/Deshboard.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

  <div class="card">
              <div class="card-header">

                <h3 class="card-title"><b>Monthly Data</b></h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>

                  <tr>
                    <th>Date</th>
                  <th>Line</th>
                  <th>Style No</th>
                  <th>Buyer</th>
                  <th>Item</th>

                  <th>OrderQty</th>
                  <th>InPut</th>
                  <th>Daily Output</th>
                  <th>Balance Qty</th>
                  <th>CMP</th>
                  <th>CMPbyStyle</th>
                    <th>CMPbyLine</th>
                   <th>Operator/Helper</th>
                    <th>CMPprHr</th>
                    <th>CMP-hr/prs</th>
                  </tr>

                  </thead>
                  <tbody>
                  {% for d in queryset %}
                <tr>
                  <td>{{d.Date}}</td>
                  <td>{{d.Line}}</td>
                  <td>{{d.Style}}</td>
                  <td> {{d.Buyer}}</td>
                  <td>{{d.Item}}</td>

                  <td>{{d.OrderQty}}</td>
                  <td>{{d.In_Put}}</td>
                  <td>{{d.DailyOutput}}</td>
                  <td>{{d.BalanceQty}}</td>
                  <td>{{d.CMP}}</td>
                  <td>{{d.DailyCMPbyStyle}}</td>
                  <td>{{d.DailyCMPbyLine}}</td>
                  <td>{{d.Operator}}/{{d.Helper}}</td>
                  <td>{{d.CMPprHr}}</td>
                  <td>{{d.CMP_Hour_Person}}</td>
                </tr>
                {% endfor %}

                  </tbody>
                  <tfoot>
                  <tr>
                    <th></th>
                    <th></th>
                  <th></th>
                  <th></th>
                  <th>Grand Totol</th>
                  <th>{{sum_orderqty}}</th>
                  <th>{{sum_input}}</th>
                  <th>{{sum_output}}</th>
                  <th>{{sum_balance}}</th>
                  <th>{{sum_cmp}}</th>
                  <th>{{sum_bystyle}}</th>
                  <th>{{sum_byline}}</th>
                    <th>{{sum_operator}}/{{sum_helper}}</th>
                  <th>{{sum_cmpprhr}}</th>
                    <th>{{sum_cmphrpr}}</th>
                  </tr>

                  </tfoot>
                </table>
              </div>
              <!-- /.card-body -->
            </div>




{% endblock content %}
<!--================== end content=============-->

myproject/templates/FilterbyStyleReport.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{{sum_of_orderqty}}


  <div class="card">
              <div class="card-header">
                <form method="POST">{% csrf_token %}



                    FROM DATE: <input type="date" name="from" class="form-control col-md-3"/>

                    TO DATE:<input type="date" class="form-control col-md-3" name="to"/>
                  <hr>
                  SELECT STYLE
                  <select class="col-md-3 form-control select2bs4" style="width: 100%;" name="style">
                    <option selected="selected"></option>
                    {% for d in style %}
                    <option>{{d.StyleCode}}</option>
                    {% endfor %}

                  </select>
                  <hr>
<input type="submit" class="form-control col-md-3 btn btn-outline-success" value="Filter by Style Code">
<!--                <h3 class="card-title">DataTable with default features</h3>-->
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>

                  <tr>
                    <th>Date</th>
                  <th>Line</th>
                  <th>Style No</th>
                  <th>Buyer</th>
                  <th>Item</th>

                  <th>OrderQty</th>
                  <th>InPut</th>
                  <th>Daily Output</th>
                  <th>Balance Qty</th>
                  <th>CMP</th>
                  <th>CMPbyStyle</th>
                    <th>CMPbyLine</th>
                   <th>Operator/Helper</th>
                    <th>CMPprHr</th>
                    <th>CMP-hr/prs</th>
                  </tr>

                  </thead>
                  <tbody>
                  {% for d in data %}
                <tr>
                  <td><a href="{% url 'myapp:DataEntryEdit' d.id %}">{{d.Date}}</a></td>
                  <td>{{d.Line}}</td>
                  <td>{{d.Style}}</td>
                  <td> {{d.Buyer}}</td>
                  <td>{{d.Item}}</td>

                  <td>{{d.OrderQty}}</td>
                  <td>{{d.In_Put}}</td>
                  <td>{{d.DailyOutput}}</td>
                  <td>{{d.BalanceQty}}</td>
                  <td>{{d.CMP}}</td>
                  <td>{{d.DailyCMPbyStyle}}</td>
                  <td>{{d.DailyCMPbyLine}}</td>
                  <td>{{d.Operator}}/{{d.Helper}}</td>
                  <td>{{d.CMPprHr}}</td>
                  <td>{{d.CMP_Hour_Person}}</td>
                </tr>
                {% endfor %}

                  </tbody>
                  <tfoot>
                  <tr>
                    <th></th>
                    <th></th>
                  <th></th>
                  <th></th>
                  <th>Grand Totol</th>
                  <th>{{filter_sum_orderqty}}</th>
                  <th>{{filter_sum_input}}</th>
                  <th>{{filter_sum_dailyoutput}}</th>
                  <th>{{filter_balanceqty}}</th>
                  <th>{{filter_cmp}}</th>
                  <th>{{filter_cmpbystyle}}</th>
                  <th>{{filter_cmpbyline}}</th>
                    <th>{{filter_operator}}/{{filter_helper}}</th>
                  <th>{{filter_cmprhr}}</th>
                    <th>{{filter_cmphrprs}}</th>
                  </tr>

                  </tfoot>
                </table>
              </div>
              <!-- /.card-body -->
            </div>




{% endblock content %}

myproject/templates/InputQtyCreate.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="card border-success mb-3" style="max-width: 50rem;">
  <div class="card-header bg-success">Create Input Qty</div>
  <div class="card-body text-success">
<form method="POST">{% csrf_token %}
    <div class="col-md-12">
                <div class="form-group">
                  <label>Date</label>
                  <input type="date" class="form-control" name="date">
                </div>
              </div>



              <div class="col-md-12">
                <div class="form-group">
                  <label>Line No</label>
                  <select class="form-control select2bs4" style="width: 100%;" name="line">
                    <option selected="selected"></option>
                    {% for b in line %}
                    <option>{{b.Name}}</option>
                    {% endfor %}

                  </select>
                </div>
              </div>


              <div class="col-md-12">
                <div class="form-group">
                  <label>Style No</label>
                  <select class="form-control select2bs4" style="width: 100%;" name="style">
                    <option selected="selected"></option>
                    {% for s in style %}
                    <option>{{s.StyleCode}}</option>
                    {% endfor %}

                  </select>
                </div>
              </div>


    <div class="col-md-12">
                <div class="form-group">
                  <label>Input Qty</label>
                  <input type="number" class="form-control" name="inputqty">
                </div>
              </div>



     <div class="col-md-12">
<!--                <div class="form-group">-->
<!--                  <label>Date</label>-->
                  <input type="submit" name="Input Data" class="btn btn-success">
<!--                </div>-->
              </div>




</form>



  </div>
</div>

<!--=========================================-->

 <div class="card">
              <div class="card-header">

<h5>Production Input Data</h5>

              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>

                    <th>Date</th>
                  <th>Line No</th>
                  <th>Style</th>
                  <th>Input Qty</th>


                  </tr>

                  </thead>
                  <tbody>
                  {% for d in today_input %}
                <tr>
                  <td>{{d.date}}</td>
                  <td>{{d.line}}</td>
                  <td> {{d.style}}</td>
                  <td>{{d.inputqty}}</td>


                </tr>
                {% endfor %}

                  </tbody>
                  <tfoot>
                  <tr>


                  <th></th>
                  <th></th>
                  <th></th>
                  <th></th>


                  </tr>

                  </tfoot>
                </table>
              </div>
              <!-- /.card-body -->
            </div>

{% endblock content %}

myproject/templates/ItemCreate.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="card border-success mb-3" style="max-width: 50rem;">
  <div class="card-header bg-success">Item Name</div>
  <div class="card-body text-success">
<form method="POST">{% csrf_token %}

    <div class="col-md-12">
                <div class="form-group">
                  <label>Item Name</label>
                  <input type="text" class="form-control" name="ItemName">
                </div>
              </div>





     <div class="col-md-12">
<!--                <div class="form-group">-->
<!--                  <label>Date</label>-->
                  <input type="submit" name="Create" class="btn btn-success">
<!--                </div>-->
              </div>




</form>



  </div>
</div>

<!--=========================================-->

 <div class="card">
              <div class="card-header">

<h5><b>ItemName List</b></h5>

              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>


                  <th>ItemName</th>



                  </tr>

                  </thead>
                  <tbody>
                  {% for d in item %}
                <tr>
                  <td>{{d.ItemName}}</td>



                </tr>
                {% endfor %}

                  </tbody>
                  <tfoot>
                  <tr>


                  <th></th>




                  </tr>

                  </tfoot>
                </table>
              </div>
              <!-- /.card-body -->
            </div>

{% endblock content %}

myproject/templates/MenPower.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="card border-success mb-3" style="max-width: 50rem;">
  <div class="card-header bg-success">Production Line Men Power</div>
  <div class="card-body text-primary">
<form method="POST">{% csrf_token %}
    <div class="col-md-12">
                <div class="form-group">
                  <label>Date</label>
                  <input type="date" class="form-control" name="date">
                </div>
              </div>



              <div class="col-md-12">
                <div class="form-group">
                  <label>Line No</label>
                  <select class="form-control select2bs4" style="width: 100%;" name="line">
                    <option selected="selected"></option>
                    {% for b in line %}
                    <option>{{b.Name}}</option>
                    {% endfor %}

                  </select>
                </div>
              </div>

    <div class="col-md-12">
                <div class="form-group">
                  <label>Number of Operator</label>
                  <input type="number" class="form-control" name="operator" required>
                </div>
              </div>

        <div class="col-md-12">
                <div class="form-group">
                  <label>Number of Helper</label>
                  <input type="number" class="form-control" name="helper">
                </div>
              </div>

    <div class="col-md-12">
                <div class="form-group">
                  <label>Working Hr</label>
                  <input type="number" class="form-control" name="workhr" value="11">
                </div>
              </div>




     <div class="col-md-12">
<!--                <div class="form-group">-->
<!--                  <label>Date</label>-->
                  <input type="submit" name="Input Data" class="btn btn-success">
<!--                </div>-->
              </div>




</form>



  </div>
</div>

<!--=========================================-->

 <div class="card">
              <div class="card-header">

<h5>Production Input Data</h5>

              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>

                    <th>Date</th>
                  <th>Line No</th>
                  <th>Operator</th>
                  <th>Helper</th>
                    <th>Work Hr</th>


                  </tr>

                  </thead>
                  <tbody>
                  {% for d in today_menpower %}
                <tr>
                  <td>{{d.Date}}</td>
                  <td>{{d.Line}}</td>
                  <td> {{d.Operator}}</td>
                  <td>{{d.Helper}}</td>
                    <td>{{d.WorkingHr}}</td>


                </tr>
                {% endfor %}

                  </tbody>
                  <tfoot>
                  <tr>


                  <th></th>
                  <th></th>
                  <th></th>
                  <th></th>
                  <th></th>


                  </tr>

                  </tfoot>
                </table>
              </div>
              <!-- /.card-body -->
            </div>

{% endblock content %}

myproject/templates/ProductionShfitEditForm.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="card border-success mb-3" style="max-width: 40rem;">
  <div class="card-header bg-info"><b>{{pi.line}}</b></div>
  <div class="card-body text-info">
<form method="POST" enctype="multipart/form-data">{% csrf_token %}

{{form.as_p}}

     <div class="col-md-12">
        <input type="submit" name="Input Data" class="btn btn-info">
     </div>




</form>



  </div>
</div>

<!--=========================================-->

{% endblock content %}

myproject/templates/ProductionShit.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="card border-success mb-3" style="max-width: 40rem;">
  <div class="card-header bg-success">Create Production Line Shift</div>
  <div class="card-body text-success">
<form method="POST">{% csrf_token %}
              <div class="col-md-12">
                <div class="form-group">
                  <label>Line No</label>
                  <select class="form-control select2bs4" style="width: 100%;" name="line">
                    <option selected="selected"></option>
                    {% for b in line %}
                    <option>{{b.Name}}</option>
                    {% endfor %}

                  </select>
                </div>
              </div>


              <div class="col-md-12">
                <div class="form-group">
                  <label>Style No</label>
                  <select class="form-control select2bs4" style="width: 100%;" name="style">
                    <option selected="selected"></option>
                    {% for s in style %}
                    <option>{{s.StyleCode}}</option>
                    {% endfor %}

                  </select>
                </div>
              </div>

     <div class="col-md-12">
<!--                <div class="form-group">-->
<!--                  <label>Date</label>-->
                  <input type="submit" name="Input Data" class="btn btn-success">
<!--                </div>-->
              </div>




</form>



  </div>
</div>

<!--=========================================-->

 <div class="card">
              <div class="card-header">

<h5>Production Data</h5>

              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>

                    <th>Production Line</th>
                  <th>Style Code</th>
                  <th>Output</th>
                  <th>Work Hour</th>



                  </tr>

                  </thead>
                  <tbody>
                  {% for d in ps %}
                <tr>
                  <td><a href="{% url 'myapp:ProductionShfitEdit' d.id %}" class=""><b>{{d.line}}</b></a></td>
                  <td><a href="{% url 'myapp:ProductionShfitEdit' d.id %}" class="">{{d.style}}</a></td>
                  <td>{{d.total_output}}</td>
                  <td>{{d.total_hour}}</td>


                </tr>
                {% endfor %}

                  </tbody>
                  <tfoot>
                  <tr>


                  <th></th>
                  <th></th>
                  <th></th>
                  <th></th>


                  </tr>

                  </tfoot>
                </table>
              </div>
              <!-- /.card-body -->
            </div>

{% endblock content %}

myproject/templates/StyleCreate.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="card border-success mb-3" style="max-width: 50rem;">
  <div class="card-header bg-success">Create Style</div>
  <div class="card-body text-success">
<form method="POST">{% csrf_token %}

    <div class="col-md-12">
                <div class="form-group">
                  <label>Enter Style Code</label>
                  <input type="text" class="form-control" name="StyleCode">
                </div>
              </div>



              <div class="col-md-12">
                <div class="form-group">
                  <label>Buyer</label>
                  <select class="form-control select2bs4" style="width: 100%;" name="buyer">
                    <option selected="selected"></option>
                    {% for b in buyer %}
                    <option>{{b.BuyerName}}</option>
                    {% endfor %}

                  </select>
                </div>
              </div>


     <div class="col-md-12">
<!--                <div class="form-group">-->
<!--                  <label>Date</label>-->
                  <input type="submit" name="Create" class="btn btn-success">
<!--                </div>-->
              </div>




</form>



  </div>
</div>

<!--=========================================-->

 <div class="card">
              <div class="card-header">

<h5><b>Style List</b></h5>

              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>


                  <th>Style No</th>
                  <th>Buyer</th>


                  </tr>

                  </thead>
                  <tbody>
                  {% for d in style %}
                <tr>
                  <td>{{d.StyleCode}}</td>
                  <td>{{d.Buyer}}</td>


                </tr>
                {% endfor %}

                  </tbody>
                  <tfoot>
                  <tr>


                  <th></th>
                  <th></th>



                  </tr>

                  </tfoot>
                </table>
              </div>
              <!-- /.card-body -->
            </div>

{% endblock content %}

myproject/templates/daily_report_create.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="card border-success mb-3" style="max-width: 60rem;">
  <div class="card-header bg-success">Daily Report</div>
  <div class="card-body text-primary">
<form method="POST">{% csrf_token %}
    <div class="col-md-12">
                <div class="form-group">
                  <label>Date</label>
                  <input type="date" class="form-control" name="date">
                </div>
              </div>

              <div class="col-md-12">
                <div class="form-group">
                  <label>Production Line</label>
                  <select class="form-control select2bs4" style="width: 100%;" name="line">
                    <option selected="selected"></option>
                    {% for l in line %}
                    <option>{{l.Name}}</option>
                    {% endfor %}

                  </select>
                </div>
                <!-- /.form-group -->

                <!-- /.form-group -->
              </div>

              <div class="col-md-12">
                <div class="form-group">
                  <label>Style No</label>
                  <select class="form-control select2bs4" style="width: 100%;" name="style">
                    <option selected="selected"></option>
                    {% for s in style %}
                    <option>{{s.StyleCode}}</option>
                    {% endfor %}

                  </select>
                </div>
              </div>



              <div class="col-md-12">
                <div class="form-group">
                  <label>Item</label>
                  <select class="form-control select2bs4" style="width: 100%;" name="item">
                    <option selected="selected"></option>
                    {% for i in item %}
                    <option>{{i.ItemName}}</option>
                    {% endfor %}

                  </select>
                </div>
                <!-- /.form-group -->

                <!-- /.form-group -->
              </div>

              <!-- /.col -->

              <!-- /.col -->
<!--              <div class="col-md-12">-->
<!--                <div class="form-group">-->
<!--                  <label>Input</label>-->
<!--                  <input type="text" class="form-control" name="in_put">-->
<!--                </div>-->
<!--              </div>-->
              <!-- /.col -->
              <div class="col-md-12">
                <div class="form-group">
                  <label>Daily Output</label>
                  <input type="text" class="form-control" name="out_put">
                </div>
              </div>

<!--              <div class="col-md-12">-->
<!--                <div class="form-group">-->
<!--                  <label>Operator</label>-->
<!--                  <input type="text" class="form-control" name="operatorhr">-->
<!--                </div>-->
<!--              </div>-->

<!--              <div class="col-md-12">-->
<!--                <div class="form-group">-->
<!--                  <label>Helper</label>-->
<!--                  <input type="text" class="form-control" name="helper">-->
<!--                </div>-->
<!--              </div>-->
<!--              &lt;!&ndash; /.col &ndash;&gt;-->

<!--              &lt;!&ndash; /.col &ndash;&gt;-->

<!--              &lt;!&ndash; /.col &ndash;&gt;-->
<!--              <div class="col-md-12">-->
<!--                <div class="form-group">-->
<!--                  <label>Working Hr</label>-->
<!--                  <input type="text" class="form-control" name="workhr">-->
<!--                </div>-->
<!--              </div>-->
              <!-- /.col -->
              <div class="col-md-12">
                <div class="form-group">
                  <label>Remark</label>
                  <input type="text" class="form-control" name="rmark">
                </div>
              </div>


     <div class="col-md-12">
<!--                <div class="form-group">-->
<!--                  <label>Date</label>-->
                  <input type="submit" name="Create" class="btn btn-success">
<!--                </div>-->
              </div>




</form>



  </div>
</div>
<!--=================================================================-->


 <div class="card">
              <div class="card-header">

<h5>Daily Production</h5>

              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>

                    <th>Date</th>
                  <th>Line No</th>
                  <th>Style</th>
                  <th>Item</th>
                    <th>Input</th>
                    <th>Daily Output</th>

                  </tr>

                  </thead>
                  <tbody>
                  {% for d in todaydata %}
                <tr>
                  <td>{{d.Date}}</td>
                  <td>{{d.Line}}</td>
                  <td> {{d.Style}}</td>
                  <td>{{d.Item}}</td>
                    <td>{{d.In_Put}}</td>
                    <td>{{d.DailyOutput}}</td>

                </tr>
                {% endfor %}

                  </tbody>
                  <tfoot>
                  <tr>


                  <th></th>
                  <th></th>
                  <th>Grand Totol</th>
                  <th>{{buyer_orderqty}}</th>
                      <th></th>
                      <th></th>


                  </tr>

                  </tfoot>
                </table>
              </div>
              <!-- /.card-body -->
            </div>




{% endblock content %}

myproject/templates/index.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Static Example</title>
  <style>body {font-family: Arial, sans-serif;}</style>

  <!-- jQuery -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

  <!-- Fengyuan Chen's Datepicker -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>
</head>
<body>

<!--  <input id="datepicker">-->
  <hr>
                  <form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
                    {{form}}
                    <input type="submit" class="btn btn-primary" value="Create">
                </form>

  <script>
    $(function () {
      $("#datepicker").datepicker();
    });
  </script>

</body>
</html>